import { withEvidenceIntegrity } from "./evidence-hash.js";
export const EVIDENCE_REVIEW_STATUSES = Object.freeze(["unreviewed", "in_review", "accepted", "rejected", "needs_more_evidence", "superseded", "expired"]);
export const EVIDENCE_LIFECYCLE_STATUSES = Object.freeze(["active", "superseded", "expired", "archived", "deleted", "rejected"]);
export const EVIDENCE_REVIEW_TRANSITIONS = Object.freeze({ unreviewed: ["in_review", "accepted", "rejected", "needs_more_evidence", "superseded", "expired"], in_review: ["accepted", "rejected", "needs_more_evidence", "superseded", "expired"], needs_more_evidence: ["in_review", "accepted", "rejected", "superseded", "expired"], accepted: ["superseded", "expired"], rejected: [], superseded: [], expired: [] });
function assertTime(value, label) { if (typeof value !== "string" || Number.isNaN(Date.parse(value))) throw new Error(`${label} must be an RFC3339 timestamp`); }
export function createEvidenceReview(review = {}) { if (!EVIDENCE_REVIEW_STATUSES.includes(review.reviewStatus ?? "unreviewed")) throw new Error("invalid evidence review status"); return Object.freeze({ reviewStatus: review.reviewStatus ?? "unreviewed", reviewedBy: review.reviewedBy ?? null, reviewedAt: review.reviewedAt ?? null, reviewNotes: review.reviewNotes ?? null }); }
export function assertEvidenceReviewTransition(from, to) { if (!EVIDENCE_REVIEW_TRANSITIONS[from]?.includes(to)) throw new Error(`invalid evidence review transition: ${from} -> ${to}`); return true; }
function assertIndependent(evidence, reviewer) { if (!reviewer) throw new Error("evidence reviewedBy is required"); const producers = new Set([evidence.collection?.collectedBy, evidence.assertion?.assertedBy, evidence.derivation?.generatedBy].filter(Boolean)); if (producers.has(reviewer)) throw new Error("evidence producer cannot be its verifier or reviewer"); }
export function markEvidenceReviewed(evidence, review = {}) { const status = review.reviewStatus ?? "accepted"; assertEvidenceReviewTransition(evidence.review?.reviewStatus ?? "unreviewed", status); assertIndependent(evidence, review.reviewedBy); assertTime(review.reviewedAt, "evidence reviewedAt"); return withEvidenceIntegrity({ ...evidence, review: createEvidenceReview({ ...review, reviewStatus: status }), lifecycle: Object.freeze({ ...evidence.lifecycle, status: status === "rejected" ? "rejected" : evidence.lifecycle.status, updatedAt: review.reviewedAt }) }); }
export function markEvidenceSuperseded(evidence, supersededBy, options = {}) { if (!supersededBy) throw new Error("superseding evidence id is required"); assertEvidenceReviewTransition(evidence.review.reviewStatus, "superseded"); assertTime(options.updatedAt, "evidence superseded updatedAt"); return withEvidenceIntegrity({ ...evidence, review: createEvidenceReview({ ...evidence.review, reviewStatus: "superseded", reviewedAt: options.updatedAt }), validity: Object.freeze({ ...evidence.validity, supersededBy }), lifecycle: Object.freeze({ ...evidence.lifecycle, status: "superseded", updatedAt: options.updatedAt }) }); }
export function markEvidenceExpired(evidence, options = {}) { assertEvidenceReviewTransition(evidence.review.reviewStatus, "expired"); assertTime(options.expiredAt, "evidence expiredAt"); if (!options.reason) throw new Error("evidence expiry reason is required"); return withEvidenceIntegrity({ ...evidence, review: createEvidenceReview({ ...evidence.review, reviewStatus: "expired", reviewedAt: options.expiredAt, reviewNotes: options.reason }), validity: Object.freeze({ ...evidence.validity, validUntil: evidence.validity.validUntil ?? options.expiredAt, expiryReason: options.reason }), lifecycle: Object.freeze({ ...evidence.lifecycle, status: "expired", updatedAt: options.expiredAt }) }); }
